[workspace]
members = [
  "provider",
  "waas",
]
resolver = "2"


[workspace.package]
version = "0.0.0"
edition = "2021"
repository = "https://github.com/al8n/waas"
homepage = "https://github.com/al8n/waas"
license = "Apache-2.0/MIT"
rust-version = "1.75.0"
description = "A placeholder"
